# Generated by Django 4.1.7 on 2023-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='Github',
            field=models.URLField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='Whatsapp',
            field=models.URLField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedIn',
            field=models.URLField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings2',
            field=models.CharField(max_length=10),
        ),
    ]
