# Generated by Django 4.1.7 on 2023-02-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioapp', '0002_remove_profile_about_remove_profile_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Github',
            field=models.URLField(default='github link', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Whatsapp',
            field=models.URLField(default='whatsapp link', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedIn',
            field=models.URLField(default='Linkedin link', max_length=500),
        ),
    ]
