# Generated by Django 4.1.7 on 2023-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioapp', '0003_alter_profile_github_alter_profile_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_stamp',
            field=models.DateField(auto_now=True),
        ),
    ]
